### ISSUE TITLE
Proposal: Edit/refresh (:e) buffer after file retrieve 

### ISSUE THREAD

**Issue by FedeAbella** [xixiaofinland/sf.nvim#231]
After calling `Sf.retrieve` on the current buffer, the buffer itself is not refreshed, meaning if changes are pulled, and you invoke the command, then attempt to write changes, you'll get an error. You're also not immediately aware that the pulled file is different. You'd need to call `:e` after the retrieve is finished to see the changes made.

I think we can resolve this by having the buffer refresh after the command is done (possibly before restoring the cursor position)? I see the terminal's `run` command accepts a callback, but I'm not entirely sure how we could use it to call `:e` on the buffer. Any ideas?

**Comment by xixiaofinland** [comment]
I have looked into this in the past but didn't come up with an ideal solution, I end up let it be like you described.

The challenge is that if I've updated the local file without saving and then retrieve it from the org, I want to refresh the buffer. However, `:e` won't work; I need to use `:e!`.

I think in your design, you treat the retrieved version is the "master source" comparing to a possible on-going update locally. I'm not yet sure if this is ideal?  

With the design out of the way, here is the technical part:

`raw_term.lua` handles the `run()` in [here](https://github.com/xixiaofinland/sf.nvim/blob/f34b81b8a8679b9f2da0009b142feebc2340f640/lua/sf/sub/raw_term.lua#L35) , which subsequently uses `vim.fn.termopen` [here](https://github.com/xixiaofinland/sf.nvim/blob/f34b81b8a8679b9f2da0009b142feebc2340f640/lua/sf/sub/raw_term.lua#L63)
You can have a look at `:h termopen()`.



In some `sf` use cases, when it fails to act (e.g. retrieve a file), the error is returned in `stdout` instead of `stderr`.

**Comment by xixiaofinland** [comment]
Maybe I'm over thinking. 
It's indeed a good idea to `e!` after pulling files from the org. It's the user who decided to pull and it should overwrite and refresh the local buffer automatically.
I just somehow remember it conflicts with other actions after a while then I rolled back.

We can implement it again to see how it goes? @FedeAbella
