### ISSUE TITLE
sf md list command: include label field

### ISSUE THREAD

**Issue by ognjen-vuceljic** [xixiaofinland/sf.nvim#244]
@FedeAbella  

Hello, hope you are doing well today!

When working with `sf md list` command, I wonder if we can also include the label of the metadata record we want to pull.

For example, when pulling Flows or Custom Fields, it would be useful to know what the label is, as API values can sometimes be different than actual metadata record labels.

Please consider the example below:

![image](https://github.com/user-attachments/assets/6d85a58d-3636-4bc2-8d19-58f2389fcb21)

Happy to hear your thoughts on this one!

**Comment by FedeAbella** [comment]
Hi @ognjen-vuceljic. Unfortunately, label is not something that the `sf org list metadata` command, which is what the plugin uses to build that window, returns. I think that's because not all metadata have labels? See:
![image](https://github.com/user-attachments/assets/83b82e6c-0a89-4347-8f8e-34cc1e1a3472)

**Comment by FedeAbella** [comment]
I'm looking into other `sf` commands that let you explore the org's schema. Don't know if those have labels, but maybe? But we can't do this now with what we've got. You could as in the [cli's repo](https://github.com/salesforcecli/cli) whether they can include that on the original command, and it would automatically appear in `sf.nvim`
