### ISSUE TITLE
Idea: Visualize APEX Code Coverage

### ISSUE THREAD

**Issue by ognjen-vuceljic** [xixiaofinland/sf.nvim#99]
Hi,

hope you are doing well today.

This might be hard to implement, so I will put this as an idea, and we can see what is feasible:

- when APEX tests are run, tested APEX code can be visualized so that covered lines are marked with `green`, and uncovered lines are marked with `red`color
- typical use case is when APEX test are run side-by-side with the code that we are actually testing

Idea is inspired by [Apex Code Coverage Visualizer](https://marketplace.visualstudio.com/items?itemName=modicatech.apex-code-coverage-visualizer)

VS Code demonstration (partial code export):

covered lines
![image](https://github.com/user-attachments/assets/569ef013-7b26-463a-898e-1392f8cfd090)

uncovered lines
![image](https://github.com/user-attachments/assets/4f1f38ca-8949-4376-bf39-5593441ae72f)

![image](https://github.com/user-attachments/assets/d0d65363-df80-42b8-a852-22595c9d58f8)

at the bottom of the extension, there is a button that can toggle this visualized coverage on/off

NVIM usage:
 
- vertical split, with one pane showing the APEX implementation, and the other one showing its APEX test
- test can be run via current hotkeys (or enhanced ones, if coverage visualization requires a new keymap)
- _to be discussed: does terminal need to show the test execution details, or we want visual coverage to be applied once the test is finished (e.g. vim.notify to inform us when the test has been completed)_

![image](https://github.com/user-attachments/assets/2ccaafa5-1fae-4fb7-9cb6-29c5e327b92d)

In case you feel like this is too complex or unnecessary, feel free to close the issue!

Thank you!

@xixiaofinland

**Comment by xixiaofinland** [comment]
Thanks again for the idea! @ognjen-vuceljic 

Visualizing code coverage like in the dev console has been on my mind for a while, but I haven't had the chance to finalize the workflow and UI.

Several points;

1. I don't see that the plugin "Apex Code Coverage Visualizer" can display line coverage in the file on the fly. It seems to show a panel with classes and their coverage only. Did I miss it?
2. For visualizing covered/uncovered lines, my principle is "the simpler the better". My proposal is to show only the uncovered lines, assuming the rest are covered obviously. And I prefer to use a sign icon (screenshot) over the highlighted lines because it's less visually intrusive. The downside is that it competes with other plugins such as Git or diagnostic tools that also use icons.
3. When running test in the term it displays result as human format while it needs to use JSON format when parsing the test result for this idea. I'm not sure how these two reconcile.
4. In my personal preference, I'd like to have a toggle hotkey to allow show the test coverage or not in the sign icon location in the apex. Such as `\c` is to show or hide it.
![Screenshot 2024-07-12 at 14 49 56](https://github.com/user-attachments/assets/fab9d0c9-4c28-40b2-9abf-4b260feb0bcb)

There are other nuances we can brainstorm further.

6.

**Comment by ognjen-vuceljic** [comment]
Thanks @xixiaofinland  

Hope you're not bothered by my continuous influx of ideas/requests.

Here are my answers below:

-  (no. 1) **Apex Code Coverage Visualizer** does not show the coverage on the fly. I think the only scenario where it might is if this button shown in my initial message is always toggled, and after re-running the tests you switch the focus to the APEX class that was being tested. Then the window reacts, and new highlighting is shown.  But that button in the bottom bar is toggled on/off manually.

- (no. 2) I fully agree with "the simpler, the better" approach. That being said, showing only uncovered lines would work fine! 

For transparency sake, I do prefer line highlighting over sign icons, but that's just my personal preference. I associate coverage with line highlighting, and sign icons with things like diagnostics, git hunks, etc....in any case, I will leave this decision to you, as this UI aspect is purely a personal preference :) 

- (no. 3) This part might be tricky. I guess the highlighting will feed off the test report (with `--code-coverage` flag included), meaning that we will need to read all the uncovered lines for each affected APEX class in a test, to make sure it's highlighted.

Another tricky part is that we need to be aware of APEX test context. For example, what **APEX Code Coverage Visualizer** does is that it visualizes all the APEX classes that have some coverage reported after test run. 

If we take an example of testing simple DML operation that runs through the trigger, everything from trigger to all the classes trigger uses (from top to bottom) would need to be highlighted.

Simple example (conceptual code):

`trigger CaseTrigger on Case (before insert, before update) {
     if(Trigger.isInsert && Trigger.isBefore) {
          CaseHandler.beforeInsert(Trigger.new);
     }
}


....
class CaseHandler {
 
   void beforeInsert (List<Case> newCases) {
      ....some code
   }
   
   void beforeUpdate (List<Case> newCases, Map<Id, Case> oldCases) {
      ....some code
   }
}

`

if we run the `insert cases;` we would expect coverage highlighting on both trigger level, and handler class.


- (no. 4) Would this toggle all the uncovered lines at the same time, or only the current line?  


Thanks!

**Comment by xixiaofinland** [comment]
Not at all, it's nice that you spent time brainstorming together, I appreciate it.

1. Ok, I didn't figure out how it shows the highlighted lines in Apex file. However, it's not a major concern as it should be similar to the browser dev console style.
2. I plan to support the line-highlight style if it's easy to implement in Neovim, and I'll consider adding a user configuration option to switch to an icon-style. We'll see how it goes.
3. The main challenge lies in handling two scenarios:
a) Running tests in the terminal uses a human-readable format for easier visual interpretation.
b) Running tests to show line coverage requires a JSON format for easier code interpretation.
We can't reuse the results from scenario (a) for scenario (b) due to the format discrepancy, and it's inefficient to ask users to re-run the same tests.
Regarding which lines to highlight, the `sf` test result will show a list of Apex files and their covered lines, like this:
```
result: {
  apex1: 10,11,12,55,51
  apex2: 20,21,22,25
}
```
If the opened Apex file is in this list, we can show the highlight.
4. I consider this feature to be at the editor level (on/off), rather than at the file or line level. So once the tests finishes, the coverage result is saved in a local file. If this feature is in `on`, the highlighted lines show/refresh on the opened buffer(s).

**Comment by xixiaofinland** [comment]
In addition, I still don't have a UI to select tests from multiple Apex test files, this might be a dependent feature for this idea too.

**Comment by xixiaofinland** [comment]
There are edge cases, like how to deal with tests with failures, how to run tests from multiple apex test files, etc.

**Comment by ognjen-vuceljic** [comment]
Thanks @xixiaofinland , I will try it out!

**Comment by ognjen-vuceljic** [comment]
@xixiaofinland  Here's one scenario I thought of:

How would the plugin handle situation where local neovim changes are different than the ones in the org?

Consider the following scenario:

- you write some APEX code in Neovim, and push it to the org
- you write some code again, but you DON'T push it to the org this time
- you run the test with visualized coverage included (that technically should test the code version from the first point, which is different that what you have locally in IDE)

I understand that it's the responsibility of the developer to ensure that Neovim code matches the version in the org that we're trying to test....but it might happen that code versions are different in Neovim, and in the org.

What would be the preferred outcome of the operation? 

- error message?
- warning that the code versions are different?
- something else

Thanks!

**Comment by xixiaofinland** [comment]
> How would the plugin handle situation where local neovim changes are different than the ones in the org?

It's indeed the developer's responsibility. `sf` CLI doesn't handle this situation either. It runs the tests by names you give in the target org, that's all.
By the time I was still using VSCode, it didn't have any feature to notify developers either. 

Fundamentally, telling the discrepancy between local and org involves a "file retrieving" action from the org, which is slow. I don't think developers want this extra slow action in each test run. Until `sf` offers a fast and lightweight way to communciate this on the fly, we don't have many options.

I'm open to any bright ideas though :).

**Comment by xixiaofinland** [comment]
FYI. I made some more updates, including this one below:

When the sign feature is enabled (require'sf.sign'.is_enabled()), opening a new Apex file will automatically display the signs in case it is mentioned in the previous test run with code coverage. I think this behavior is much more intuitive.

**Comment by xixiaofinland** [comment]
This feature is implemented already in `main` branch, close this thread now.
